
all: Q1 Q2 Q3 Q4 Q5 Q6 Q7

clean:
	rm -f Q1 Q2 Q3 Q4 Q5 Q6 Q7

Q1: Q1.c
	gcc -g -o Q1 Q1.c

Q2: Q2.c
	gcc -g -o Q2 Q2.c

Q3: Q3.c
	gcc -g -o Q3 Q3.c

Q4: Q4.c
	gcc -g -o Q4 Q4.c

Q5: Q5.c
	gcc -g -o Q5 Q5.c

Q6: Q6.c
	gcc -g -o Q6 Q6.c

Q7: Q7.c
	gcc -g -o Q7 Q7.c

